### ISSUE TITLE
ubuntu/budgie: ModuleNotFoundError: No module named 'sip'

### ISSUE THREAD

**Issue by gdampf** [fossasia/pslab-python#87]
Installed pslab and pslab-apps succesfully with no errors, but starting Experiments ends up in a stack-trace reg. not found modules (at least sip and apt-pkg was mentioned).
Before posting endless traces: Does anybody made the same experience?
I have several versions of python installed (2.7, 3.6 and 3.7 at least) and tried this within the 2.7-Environment as well as in 3.7, with the same result. Well, at least the 2.7 should work, as I use it also for PlatformIO, which works perfectly.
What is so special on this pslab? I don't want to create a completely isolated environment just for that.

**Comment by gdampf** [comment]
Ohhh, what a lousy description.
I managed to get some of the dependencies solved, but when starting, I got the following errors) see below).
IMHO, I struggling with versions! I'm using python3.6 and PyQt5, so I installed pyqt5-dev-tools instead of Version 4 - does this matter?

Did anybody managed to get this running on ubuntu with python 3.6 and PyQt5?

Here, the errors (the gui is displayed, but I am unable to connect to the hardware - tried all serial lines available):

$ Experiments
qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve property: linearGradient4205
qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve property: linearGradient4205
qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve property: linearGradient4205
qt.svg: /usr/share/icons/Faba/16x16/actions/dialog-ok.svg:112: Could not resolve property: linearGradient4205
Traceback (most recent call last):
  File "/usr/bin/Experiments", line 236, in changeSubSection
    self.loadParentModuleIcons(self.subSectionPaths[ind])
  File "/usr/bin/Experiments", line 247, in loadParentModuleIcons
    self.loadSubmoduleIcons(submodule)
  File "/usr/bin/Experiments", line 266, in loadSubmoduleIcons
    icon = self.experimentIcon(submodule,app,fn)
  File "/usr/lib/python3/dist-packages/PSL_Apps/utilitiesClass.py", line 1168, in __init__
    tmp = importlib.import_module(basepackage+'.'+name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/pslab/psl_res/GUI/A_TEST_AND_MEASUREMENT/A_TandM/C_stream.py", line 15, in <module>
    from templates import ui_arbitStream as arbitStream
ImportError: cannot import name 'ui_arbitStream'
16384
Releasing port
module 'serial' has no attribute 'SerialException'
Releasing port
module 'serial' has no attribute 'SerialException'
Releasing port
module 'serial' has no attribute 'SerialException'
Releasing port
module 'serial' has no attribute 'SerialException'
Releasing port
module 'serial' has no attribute 'SerialException'
